provided a remote execute option

diff --git a/test/autotest_test b/test/autotest_test
--- a/test/autotest_test
+++ b/test/autotest_test
@@ -19,14 +19,18 @@ initialize_variables ()
   Skip=0
   Build=1
   Run=2
-  
+#
+# Assume that we are started from autotest and have done 
+# a "cd ${HYPRE_AUTOTEST_DIR}", however as long as we are
+# above a "linear_solvers" directory we should be ok.
+#
   if test ! "${HYPRE_AUTOTEST_DIR}"
   then
     HYPRE_AUTOTEST_DIR=`pwd`
   else
     if [ ! -d ${HYPRE_AUTOTEST_DIR} ]
     then
-      if [ ! -d ../linear_solvers ]
+      if [ ! -d ./linear_solvers ]
       then
         echo "$0: no HYPRE_AUTOTEST_DIR environment variable"
         exit 2
@@ -35,10 +39,18 @@ initialize_variables ()
   fi
   StdBuildDir=${HYPRE_AUTOTEST_DIR}/linear_solvers
   StdTestDir=${HYPRE_AUTOTEST_DIR}/linear_solvers/test
+#
+# Define HYPRE_ARCH
+#
+. $StdTestDir/hypre_arch.sh
   if test ! "$HYPRE_MAIL"
   then
     HYPRE_MAIL=mailx
   fi
+#
+# If NOT started by autotest (hence no HYPRE_*_EMAIL variabled
+# defined) default mail to UID only.
+#
   if test ! "$HYPRE_DEFAULT_EMAIL"
   then
     User=`who am I|cut -f 1 -d \ `
@@ -58,8 +70,16 @@ initialize_variables ()
 #=============================================================================
 
 parse_arguments () { 
-  while getopts :a:b:cdfhmno:p:st:xy arg
+#
+# The getopts follows posix.2, if sh is a posix shell as
+# (as required by posix.2) then getopts is a built-in.
+# If sh is a non posix.2 or a early Bourne shell (that
+# probably implement the obsolute getopt) then
+# getopts(1) will be used.
+#
+  while getopts :a:b:cdfhmno:p:r:st:xy arg
   do
+    argcur=$arg
     case $arg in
       a) confbuildtest $OPTARG  " "             "default"   1 1 1 1 1 1;;
       b) confbuildtest $OPTARG  " "             "beta"      0 0 0 0 1 1;;
@@ -72,13 +92,14 @@ parse_arguments () {
       n) confbuildtest $Build   "--without-MPI" "no_mip"    1 1 0 1 1 0;;
       o) confbuildtest $OPTARG  "--with-openmp" "openmp"    0 0 0 0 1 0;;
       p) confbuildtest $OPTARG  "--with-petac"  "petac"	    0 0 0 1 0 0;;
+      r) HYPRE_RUN_MACHINE=$OPTARG;;
       s) confbuildtest $Build   "--with-strict-checking" \
 					 "strict_checking"  1 1 0 1 1 0;;
       t) confbuildtest $OPTARG "--with-pthreads" "pthreads" 1 0 0 0 0 0;;
       x) build $Build   "beta++" "beta++" "test";;
       y) build $Build   "beta77" "beta77" "test";;
-      :) echo "$0: \"$OPTARG\" requires a value"; exit 2;;
-     \?) echo "$0: INVALID option \"$OPTARG\" at $OPTIND"; exit 2;;
+      :) echo "$0: \"$argcur\" requires a value"; exit 2;;
+     \?) echo "$0: INVALID option \"$argcur\" at $OPTIND"; exit 2;;
     esac
   done
   shift `expr $OPTIND - 1`
@@ -90,36 +111,37 @@ parse_arguments () {
 #=============================================================================
 usage () {
   printf "Usage: %s [-cdfhmns] [-a opt] [-b opt]\n" $0
-  printf "       [-o opt] [-p opt] [-t opt]\n"
+  printf "       [-o opt] [-p opt] [-r host] [-t opt]\n"
   printf "\n"
-  printf "Hypre autotest (Note: all options executed in the same\n"
-  prinf  "left-to-right order as entered).\n"
+  printf "Hypre autotest (Note: all options are positional dependent\n"
+  printf "i.e., options are sequentially executed in left-to-right order).\n"
   printf "\n"
   printf "Options for the "opt" argument are "0", "1", or "2" where:\n"
   printf "  1=skip (ignore this test),\n"
   printf "  2=configure and make, and\n"
   printf "  3=configure, make and run.\n"
   printf "\n"
-  printf "-a opt   All; perform the (default) configure, make, and execute.\n"
-  printf "         Performs make struct, IJ, fei, all, beta, nofei, and\n"
+  printf "-a opt   All; the (default) configure, make, and execute. Also\n"
+  printf "         performs make struct, IJ, fei, all, beta, nofei, and\n"
   printf "         fei++, followed by the test_drivers script (when opt=2).\n"
   printf "-b opt   Beta; perform the (default) configure, make beta, nofei,\n"
   printf "         fei++, followed by the test_drivers script (when opt=2).\n"
-  printf "-c       C++; perform make all++ (no configure, or execute).\n"
+  printf "-c       C++; make all++ (no configure, or execute).\n"
   printf "-d       Docs; makes the documentation directory.\n"
-  printf "-f       F77; perform make all77 (no configure, or execute).\n"
+  printf "-f       F77; make all77 (no configure, or execute).\n"
   printf "-h       Help; display this help message.\n"
   printf "-m       Mail; mail errors to developers.\n"
   printf "+m       NoMail; Don\'t send any mail.\n"
-  printf "-n       Beta; perform configure --without-MPI, make struct, IJ,\n"
+  printf "-n       NoMPI; configure --without-MPI, make struct, IJ,\n"
   printf "         all, and beta (no execute option).\n"
-  printf "-o opt   openMP; perform configure --with-openmp, make beta.\n"
+  printf "-o opt   openMP; configure --with-openmp, make beta.\n"
   printf "-p opt   PETSc; perform configure --with-petsc, make all.\n"
-  printf "-s       Strict; perform configure --with-strict-checking,\n"
+  printf "-r host  Remote; remote exection on "host".\n"
+  printf "-s       Strict; configure --with-strict-checking,\n"
   printf "         followed by make struct, IJ, all, beta(no execute option).\n"
   printf "-t opt   Thread; perform configure --with-pthreads, make struct.\n"
-  printf "-x       BetaC++; perform make beta++ (no configure, or execute).\n"
-  printf "-y       BetaF77; perform make beta77 (no configure, or execute).\n"
+  printf "-x       BetaC++; make beta++ (no configure, or execute).\n"
+  printf "-y       BetaF77; make beta77 (no configure, or execute).\n"
 }
 
 #=============================================================================
@@ -140,14 +162,15 @@ mail_errors () {
         else
           RECIPIENTS=$HYPRE_DEFAULT_EMAIL
         fi
-        ${HYPRE_MAIL} -s "Autotest error: $i" $RECIPIENTS < $i 
+        SUBJECT="Autotest error: ${i} ($HYPRE_ARCH)"
+        ${HYPRE_MAIL} -s $SUBJECT $RECIPIENTS < $i 
       fi 
     done 
   fi
 }
 
 cleanup () { 
-  echo "in cleanup"
+  echo "Autotest finished leaving $0"
 }
 #=============================================================================
 # General purpose function for configure, make and execute
@@ -160,7 +183,7 @@ StructOpt=$4	 IJOpt=$5	 FeiOpt=$6
 MakeOpt=$7	 BetaOpt=$8	 NoFeiOpt=$9
 if [ ${BuildOpt} -ne $Skip ]
 then
-  echo "Starting configure and make of $MessageStr"
+  echo "Autotest starting configure and make of $MessageStr"
   if [ ${BuildOpt} -eq $Build -o ${BuildOpt} -eq $Run ]
   then
     cd $StdBuildDir
@@ -205,16 +228,27 @@ then
   fi
   if [ ${BuildOpt} -eq $Run ]
   then
-    echo "Starting execution of $MessageStr"
+    echo "Autotest starting execution of $MessageStr"
     if [ $NoFeiOpt -ne $Skip ]
     then
       $MAKE nofei
       cd $HYPRE_AUTOTEST_DIR/linear_solvers/test
       $MAKE fei++
     fi
-    cd $HYPRE_AUTOTEST_DIR/linear_solvers/test
-    ./test_drivers.sh $MailOpt
+    if test ! "${HYPRE_RUN_MACHINE}"
+    then
+      cd $HYPRE_AUTOTEST_DIR/linear_solvers/test
+      ./test_drivers.sh $MailOpt
+    else
+      ssh ${HYPRE_RUN_MACHINE} "\
+      (\
+        cd ${HYPRE_AUTOTEST_DIR}/linear_solvers/test;\
+        . ./env.${HYPRE_ARCH};\
+        ./test_drivers.sh $MailOpt\
+    )"
+    fi
   fi
+  echo "Autotest finished $MessageStr"
 fi
 }
 #=============================================================================
@@ -226,11 +260,12 @@ build ()
 BuildOpt=$1	 MakeOption=$2	 MessageStr=$3	MakeDir=$4
 if [ $BuildOpt -ne $Skip ]
 then
-  echo "Starting make of $MessageStr"
+  echo "Autotest starting make of $MessageStr"
   cd $StdBuildDir/$MakeDir
   $MAKE $MakeOption 1> ${Hdr}.${MessageStr}.log \
 	2> ${Hdr}.${MessageStr}.err
   echo "$HYPRE_DEFAULT_EMAIL" > ${Hdr}.${MessageStr}.err.email
+  echo "Autotest finished $MessageStr"
 fi
 }
 
@@ -241,4 +276,4 @@ fi
 initialize_variables
 parse_arguments $*
 mail_errors
-#cleanup
+cleanup
