Corrections/updates to config/build changes.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -8091,7 +8091,6 @@ then
 
 
   hypre_blas_ok=no
-  BLASLIBS=""
 
 
 # Check whether --with-blas or --without-blas was given.
@@ -8130,7 +8129,7 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
   hypre_blas_save_LIBS="$LIBS"
   LIBS="$LIBS $FLIBS"
 
-# First, check BLASLIBS environment variable
+# Is BLASLIBS environment variable set?
   if test $hypre_blas_ok = no; then
     if test "x$BLASLIBS" != x; then
 	save_LIBS="$LIBS"; LIBS="$BLASLIBS $LIBS"
@@ -8306,10 +8305,91 @@ fi
 echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_var'}'`" >&5
 echo "${ECHO_T}`eval echo '${'$as_ac_var'}'`" >&6
 if test `eval echo '${'$as_ac_var'}'` = yes; then
-  hypre_blas_ok=yes
+  hypre_blas_ok=yes; BLASLIBS="$LIBS"
 fi
 
 	LIBS="$save_LIBS"
+  fi
+
+# Generic BLAS library?
+  if test $hypre_blas_ok = no; then
+	as_ac_Lib=`echo "ac_cv_lib_blas_$dgemm" | $as_tr_sh`
+echo "$as_me:$LINENO: checking for $dgemm in -lblas" >&5
+echo $ECHO_N "checking for $dgemm in -lblas... $ECHO_C" >&6
+if eval "test \"\${$as_ac_Lib+set}\" = set"; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lblas  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char $dgemm ();
+#ifdef F77_DUMMY_MAIN
+
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+
+#endif
+int
+main ()
+{
+$dgemm ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  eval "$as_ac_Lib=yes"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+eval "$as_ac_Lib=no"
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_Lib'}'`" >&5
+echo "${ECHO_T}`eval echo '${'$as_ac_Lib'}'`" >&6
+if test `eval echo '${'$as_ac_Lib'}'` = yes; then
+  hypre_blas_ok=yes; BLASLIBS="-lblas"
+fi
+
   fi
 
 # BLAS in ATLAS library? (http://math-atlas.sourceforge.net/)
@@ -9118,87 +9198,6 @@ fi
 
   fi
 
-# Generic BLAS library?
-  if test $hypre_blas_ok = no; then
-	as_ac_Lib=`echo "ac_cv_lib_blas_$dgemm" | $as_tr_sh`
-echo "$as_me:$LINENO: checking for $dgemm in -lblas" >&5
-echo $ECHO_N "checking for $dgemm in -lblas... $ECHO_C" >&6
-if eval "test \"\${$as_ac_Lib+set}\" = set"; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  ac_check_lib_save_LIBS=$LIBS
-LIBS="-lblas  $LIBS"
-cat >conftest.$ac_ext <<_ACEOF
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-
-/* Override any gcc2 internal prototype to avoid an error.  */
-#ifdef __cplusplus
-extern "C"
-#endif
-/* We use char because int might match the return type of a gcc2
-   builtin and then its argument prototype would still apply.  */
-char $dgemm ();
-#ifdef F77_DUMMY_MAIN
-
-#  ifdef __cplusplus
-     extern "C"
-#  endif
-   int F77_DUMMY_MAIN() { return 1; }
-
-#endif
-int
-main ()
-{
-$dgemm ();
-  ;
-  return 0;
-}
-_ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
-  (eval $ac_link) 2>conftest.er1
-  ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_c_werror_flag"
-			 || test ! -s conftest.err'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; } &&
-	 { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  eval "$as_ac_Lib=yes"
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-eval "$as_ac_Lib=no"
-fi
-rm -f conftest.err conftest.$ac_objext \
-      conftest$ac_exeext conftest.$ac_ext
-LIBS=$ac_check_lib_save_LIBS
-fi
-echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_Lib'}'`" >&5
-echo "${ECHO_T}`eval echo '${'$as_ac_Lib'}'`" >&6
-if test `eval echo '${'$as_ac_Lib'}'` = yes; then
-  hypre_blas_ok=yes; BLASLIBS="-lblas"
-fi
-
-  fi
-
   LIBS="$hypre_blas_save_LIBS"
 
   if test $hypre_blas_ok = no; then
@@ -9216,7 +9215,7 @@ echo "$as_me: WARNING: Cannot find BLAS library" >&2;}
 echo "$as_me: WARNING:   configuring --without-blas" >&2;}
       { echo "$as_me:$LINENO: WARNING: ***************************************" >&5
 echo "$as_me: WARNING: ***************************************" >&2;}
-      BLAS_DIR="`pwd`/lib"
+      BLAS_DIR="`pwd`/hypre/lib"
       BLASLIBDIRS="-L $BLAS_DIR"
       BLASLIBS="-lHYPRE_utilities"
       BLASNEEDED=
@@ -9227,7 +9226,7 @@ _ACEOF
 
    elif test "$BLASLIBS" = "internal"
    then
-      BLAS_DIR="`pwd`/lib"
+      BLAS_DIR="`pwd`/hypre/lib"
       BLASLIBDIRS="-L $BLAS_DIR"
       BLASLIBS="-lHYPRE_utilities"
       BLASNEEDED=
@@ -9252,7 +9251,6 @@ then
 
 
   hypre_lapack_ok=no
-  LAPACKLIBS=""
 
 
 # Check whether --with-lapack or --without-lapack was given.
@@ -9288,12 +9286,12 @@ ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $
 ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 
-  hypre_lapack_save_LIBS="$LIBS"
+  hypre_lapack_save_libs="$LIBS"
 
-# First, check LAPACKLIBS environment variable
+# Is LAPACKLIBS environment variable set?
   if test $hypre_lapack_ok = no; then
     if test "x$LAPACKLIBS" != x; then
-        save_LIBS="$LIBS"; LIBS="$LAPACKLIBS $BLASLIBS $LIBS $FLIBS"
+        save_LIBS="$LIBS"; LIBS="$LAPACKLIBS $LIBS"
         echo "$as_me:$LINENO: checking for $dsygv in $LAPACKLIBS" >&5
 echo $ECHO_N "checking for $dsygv in $LAPACKLIBS... $ECHO_C" >&6
         cat >conftest.$ac_ext <<_ACEOF
@@ -9363,7 +9361,7 @@ echo "${ECHO_T}$hypre_lapack_ok" >&6
     fi
   fi
 
-# LAPACK linked to by default?  (is sometimes included in BLAS lib)
+# LAPACK included in BLAS lib?
   if test $hypre_lapack_ok = no; then
         save_LIBS="$LIBS"; LIBS="$LIBS $BLASLIBS $FLIBS"
         as_ac_var=`echo "ac_cv_func_$dsygv" | $as_tr_sh`
@@ -9466,24 +9464,139 @@ fi
 echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_var'}'`" >&5
 echo "${ECHO_T}`eval echo '${'$as_ac_var'}'`" >&6
 if test `eval echo '${'$as_ac_var'}'` = yes; then
-  hypre_lapack_ok=yes
+  hypre_lapack_ok=yes; LAPACKLIBS="$BLASLIBS"
 fi
 
         LIBS="$save_LIBS"
   fi
 
-# Generic LAPACK library?
-  for lapack in lapack lapack_rs6k; do
-        if test $hypre_lapack_ok = no; then
-                save_LIBS="$LIBS"; LIBS="$BLASLIBS $LIBS"
-                as_ac_Lib=`echo "ac_cv_lib_$lapack''_$dsygv" | $as_tr_sh`
-echo "$as_me:$LINENO: checking for $dsygv in -l$lapack" >&5
-echo $ECHO_N "checking for $dsygv in -l$lapack... $ECHO_C" >&6
+# LAPACK linked to by default?
+  if test $hypre_lapack_ok = no; then
+        save_LIBS="$LIBS"; LIBS="$LIBS"
+        as_ac_var=`echo "ac_cv_func_$dsygv" | $as_tr_sh`
+echo "$as_me:$LINENO: checking for $dsygv" >&5
+echo $ECHO_N "checking for $dsygv... $ECHO_C" >&6
+if eval "test \"\${$as_ac_var+set}\" = set"; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+/* Define $dsygv to an innocuous variant, in case <limits.h> declares $dsygv.
+   For example, HP-UX 11i <limits.h> declares gettimeofday.  */
+#define $dsygv innocuous_$dsygv
+
+/* System header to define __stub macros and hopefully few prototypes,
+    which can conflict with char $dsygv (); below.
+    Prefer <limits.h> to <assert.h> if __STDC__ is defined, since
+    <limits.h> exists even on freestanding compilers.  */
+
+#ifdef __STDC__
+# include <limits.h>
+#else
+# include <assert.h>
+#endif
+
+#undef $dsygv
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+{
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char $dsygv ();
+/* The GNU C library defines this for functions which it implements
+    to always fail with ENOSYS.  Some functions are actually named
+    something starting with __ and the normal name is an alias.  */
+#if defined (__stub_$dsygv) || defined (__stub___$dsygv)
+choke me
+#else
+char (*f) () = $dsygv;
+#endif
+#ifdef __cplusplus
+}
+#endif
+
+#ifdef F77_DUMMY_MAIN
+
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+
+#endif
+int
+main ()
+{
+return f != $dsygv;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  eval "$as_ac_var=yes"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+eval "$as_ac_var=no"
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_var'}'`" >&5
+echo "${ECHO_T}`eval echo '${'$as_ac_var'}'`" >&6
+if test `eval echo '${'$as_ac_var'}'` = yes; then
+  hypre_lapack_ok=yes; LAPACKLIBS="$LIBS"
+fi
+
+        LIBS="$save_LIBS"
+  fi
+
+# Generic LAPACK library
+  if test $hypre_lapack_ok = no; then
+     if test "$BLASLIBS" = "-lHYPRE_utilities"; then
+       TEMPBLAS=
+     else
+       TEMPBLAS="$BLASLIBS"
+     fi
+     save_LIBS="$LIBS"; LIBS="$LIBS $FLIBS"
+     save_LDFLAGS="$LDFLAGS"
+     LDFLAGS="-L/usr/lib -L/usr/local/lib $LDFLAGS"
+     as_ac_Lib=`echo "ac_cv_lib_lapack_$dsygv" | $as_tr_sh`
+echo "$as_me:$LINENO: checking for $dsygv in -llapack" >&5
+echo $ECHO_N "checking for $dsygv in -llapack... $ECHO_C" >&6
 if eval "test \"\${$as_ac_Lib+set}\" = set"; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   ac_check_lib_save_LIBS=$LIBS
-LIBS="-l$lapack $FLIBS $LIBS"
+LIBS="-llapack $TEMPBLAS $LIBS"
 cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
@@ -9550,12 +9663,100 @@ fi
 echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_Lib'}'`" >&5
 echo "${ECHO_T}`eval echo '${'$as_ac_Lib'}'`" >&6
 if test `eval echo '${'$as_ac_Lib'}'` = yes; then
-  hypre_lapack_ok=yes; LAPACKLIBS="-l$lapack"
+  hypre_lapack_ok=yes; LAPACKLIBS="-llapack"
 fi
 
-                LIBS="$save_LIBS"
-        fi
-  done
+     LIBS="$save_LIBS"
+     LDFLAGS="$save_LDFLAGS"
+  fi
+
+# Generic LAPACK_RS6K library
+  if test $hypre_lapack_ok = no; then
+     save_LIBS="$LIBS"; LIBS="$LIBS $FLIBS"
+     save_LDFLAGS="$LDFLAGS"
+     LDFLAGS="-L/usr/lib -L/usr/local/lib $LDFLAGS"
+     as_ac_Lib=`echo "ac_cv_lib_lapack_rs6k_$dsygv" | $as_tr_sh`
+echo "$as_me:$LINENO: checking for $dsygv in -llapack_rs6k" >&5
+echo $ECHO_N "checking for $dsygv in -llapack_rs6k... $ECHO_C" >&6
+if eval "test \"\${$as_ac_Lib+set}\" = set"; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-llapack_rs6k $BLASLIBS $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char $dsygv ();
+#ifdef F77_DUMMY_MAIN
+
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+
+#endif
+int
+main ()
+{
+$dsygv ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  eval "$as_ac_Lib=yes"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+eval "$as_ac_Lib=no"
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_Lib'}'`" >&5
+echo "${ECHO_T}`eval echo '${'$as_ac_Lib'}'`" >&6
+if test `eval echo '${'$as_ac_Lib'}'` = yes; then
+  hypre_lapack_ok=yes; LAPACKLIBS="-llapack_rs6k"
+fi
+
+     LIBS="$save_LIBS"
+     LDFLAGS="$save_LDFLAGS"
+  fi
+
+  LIBS="$hypre_lapack_save_libs"
 
 if test $hypre_lapack_ok = no; then
          LAPACKLIBS="no"
@@ -9572,7 +9773,7 @@ echo "$as_me: WARNING: Cannot find LAPACK library" >&2;}
 echo "$as_me: WARNING:   configuring --without-lapack" >&2;}
       { echo "$as_me:$LINENO: WARNING: ***************************************" >&5
 echo "$as_me: WARNING: ***************************************" >&2;}
-      LAPACK_DIR="`pwd`/lib"
+      LAPACK_DIR="`pwd`/hypre/lib"
       LAPACKLIBDIRS="-L $LAPACK_DIR"
       LAPACKLIBS="-lHYPRE_utilities"
       LAPACKNEEDED=
@@ -9583,7 +9784,7 @@ _ACEOF
 
    elif test "$LAPACKLIBS" = "internal"
    then
-      LAPACK_DIR="`pwd`/lib"
+      LAPACK_DIR="`pwd`/hypre/lib"
       LAPACKLIBDIRS="-L $LAPACK_DIR"
       LAPACKLIBS="-lHYPRE_utilities"
       LAPACKNEEDED=
