Added `all', `install', `clean', and `veryclean' targets.

diff --git a/Makefile.in b/Makefile.in
--- a/Makefile.in
+++ b/Makefile.in
@@ -12,7 +12,7 @@ SHELL = /bin/sh
 srcdir = @srcdir@
 VPATH = @srcdir@
 
-HYPRE_SUBDIRS =\
+HYPRE_DIRS =\
  utilities\
  struct_matrix_vector\
  struct_linear_solvers\
@@ -20,16 +20,48 @@ HYPRE_SUBDIRS =\
 
 all:
 	@ \
-	for i in ${HYPRE_SUBDIRS}; \
+	for i in ${HYPRE_DIRS}; \
 	do \
 	echo "Making $$i ..."; \
 	(cd $$i; make); \
 	echo ""; \
 	done
 
+install:
+	@ \
+	# check that HYPRE_INSTALL_DIR is defined; \
+	if [ ! "$$HYPRE_INSTALL_DIR" ]; \
+	then \
+	   echo "Error: set the HYPRE_INSTALL_DIR environment variable"; \
+	   exit 1; \
+	fi; \
+	# Check that the install directory exists; \
+	if [ ! -d $$HYPRE_INSTALL_DIR ]; \
+	then \
+	   echo "Error: no directory HYPRE_INSTALL_DIR=$$HYPRE_INSTALL_DIR"; \
+	   exit 1; \
+	fi; \
+	# create install subdirectories; \
+	( \
+	   cd $$HYPRE_INSTALL_DIR; \
+	   DIRS="bin docs include lib"; \
+	   for i in $$DIRS; \
+	   do \
+	      rm -fr $$i; \
+	      mkdir $$i; \
+	   done \
+	); \
+	# install the libraries; \
+	for i in ${HYPRE_DIRS}; \
+	do \
+	echo "Installing $$i ..."; \
+	(cd $$i; make install); \
+	echo ""; \
+	done
+
 clean:
 	@ \
-	for i in ${HYPRE_SUBDIRS}; \
+	for i in ${HYPRE_DIRS}; \
 	do \
 	echo "Cleaning $$i ..."; \
 	(cd $$i; make clean); \
@@ -37,9 +69,9 @@ clean:
 
 veryclean:
 	@ \
-	for i in ${HYPRE_SUBDIRS}; \
+	for i in ${HYPRE_DIRS}; \
 	do \
-	echo "Really cleaning $$i ..."; \
+	echo "Very-cleaning $$i ..."; \
 	(cd $$i; make veryclean); \
 	done
 
